org: markaxelus
app: revision
service: my-lambda-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  chainedLambda:
    timeout: 60

    handler: index.handler
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    events:
      - http:
          path: test
          method: post
          cors: true

plugins:
  - serverless-offline
